### PR TITLE
Add gradle and Tests

### PR DESCRIPTION
**Pull request by seymourpoler**
This PR belongs to issue #9 
We have added `Gradle` as a dependency manager.
We have added several tests, to verify that everything is all right.

### CODE REVIEW

**Comment by VerisimilitudeX** [comment]
Could you please fix the merge conflicts @seymourpoler? Thanks.

**Review by VerisimilitudeX — CHANGES_REQUESTED** [review]
@seymourpoler please fix merge conflicts! Thanks!

**Comment by seymourpoler** [comment]
Hi @VerisimilitudeX ,
The branch is updated with the lastest changes from the main branch.
I think that It is ready to be merged.
Many thanks 👍

**Review by VerisimilitudeX — APPROVED** [review]

**Comment by VerisimilitudeX** [comment]
This looks perfect, thanks @seymourpoler! 

I would also really appreciate it if you could star the DNAnalyzer repository (https://github.com/VerisimilitudeX/DNAnalyzer) to show your support, if you haven't done so already. I (or another member from our team) will review your PR in the next 48 hours, and will get back to you. If you have any questions, please join our Discord server: https://discord.gg/X3YCvGf2Ug.

**Pull request merged**
